// <auto-generated />
namespace data_pharm_softwere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AccountModal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Account));

        string IMigrationMetadata.Id
        {
            get { return "202508131129429_AccountModal"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
