// <auto-generated />
namespace data_pharm_softwere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SeedProductIdStart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedProductIdStart));
        
        string IMigrationMetadata.Id
        {
            get { return "202506190620331_SeedProductIdStart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
